# coding: utf-8

name: Build lefaso-scraper docker Image

run-name: Build trigged by ${{github.actor}}

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docker Image
        run: |
          docker build . -t lefaso-scraper
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker tag lefaso-scraper ${{ secrets.DOCKER_HUB_USERNAME }}/lefaso-scraper
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/lefaso-scraper:latest
