# coding: utf-8

name: Test

run-name: Test Workflow

on:
  push:
    branches:
      - "master"
  schedule:
      - cron:  '0 14 */3 * *'

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          sudo apt-get update
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install
          export PATH=".venv/bin:$PATH"
          make flake8
          make mypy
          make pytest
