# coding: utf-8

name: Test lefaso-scraper

run-name: Trigged by ${{github.actor}}

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          flake8 .
