# coding: utf-8

name: test-lefaso-scraper

run-name: trigged by ${{github.actor}}

on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          sudo apt-get update
          sudo curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.in-project true
          poetry install
          export PATH=".venv/bin:$PATH"
          make flake8
          make mypy
          make pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
